name: Test Runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build the Docker image with ocaml
        run: docker build . --file Dockerfile --tag test-runner

      - name: Test
        run: docker run -v $(pwd)/test_percentage.txt:/workspace/test_percentage.txt test-runner

      - name: Check
        run: |
          ls -al
          make check