name: Test Runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build the Docker image with ocaml
        run: docker build . --file Dockerfile --tag ocamlbuild

      - name: Test
        run: |
          make clean
          docker run -v $(pwd)/:/workspace ocamlbuild test.native
          ls -al
          ./test.native

      - name: Check
        run: |
          ls -al
          make check